### ISSUE TITLE
error in era5_calcs.py line 113

### ISSUE THREAD

**Issue by kelliecook** [lcarlaw/era5#1]
Hi,

I'm using your era5_calc script to calculate pressure levels for my ERA5 model level dataset (thanks for putting this on github!).
One line 113 Ph_lev and Ph_levplusone are both arrays and an error is created when they are assigned to an element of the array pres. I just wanted to check if this implementation is correct.

Thanks!

**Comment by lcarlaw** [comment]
Hi Kellie-

Both the lnsp and z arrays, while both 4-d (longitude, latitude, level, time), only have data stored for the surface level, with NaNs filling out the rest of the matrix. `calc_z_and_p` expects a vector of `tk` and `q` (the length of which is the same as the `levels` array), while `z` and `lnsp` are individual floats corresponding to the surface values (i.e. ignoring the NaN values). It sounds like you might be passing the entire `z` and `lnsp` vector into the `calc_z_and_p` function which is causing your error. 

If you're reading your data in with xarray, I think you'll need to do something like the following:

```
import utils.era5_calcs as calcs
import xarray as xr

ds = xr.open_dataset('...nc')
lnsp = ds.lnsp.values
z = ds.z.values
tk = ds.t.values
q = ds.q.values
levels = ds.level.values

i,j,t = 0,0,0
hght, pres = calcs.calc_z_and_p(lnsp[t,j,0,i], tk[t,:,j,i], q[t,:,j,i], z[t,0,j,i], levels)
```

Let me know if that helps. Much of this code wasn't necessarily written to be extensible to other projects, at least in its current form, but hopefully you can find some useful bits in the various functions!

**Comment by kelliecook** [comment]
Hi Lee,

Yes, thank you so much for the explanation. I have successfully implemented this correction into my code with a slight correction to the last line and it now works for me:

calc_z_and_p(lnsp[t,0,j,i], tk[t,:,j,i], q[t,:,j,i], z[t,0,j,i], levels)

A huge thank you for sharing your code on github and for your quck response!

Kellie.
